package sWave;

/**
 *
 * @author Brian Millar
 */
public class Graphics {
    public static String s_cart = "<svg id=\"cartIcon\" onclick=\"window.location.assign('cart.jsp')\" viewBox=\"0 0 100 100\">\n<circle class=\"iconCircleFilled\" cx=\"78\" cy=\"24\" r=\"4\"/>\n<rect class=\"iconRectFilled\" x=\"76\" y=\"22\" width=\"4\" height=\"8\"/>\n<polygon class=\"iconPolyFilled\" points=\"15,30 25,70 70,70 80,30\"/>\n<rect class=\"iconRectFilled\" x=\"64\" y=\"65\" width=\"4\" height=\"12\"/>\n<rect class=\"iconRectFilled\" x=\"33\" y=\"75\" width=\"37\" height=\"4\"/>\n<circle class=\"iconCircleFilled\" cx=\"33\" cy=\"78\" r=\"5\"/>\n<circle class=\"iconCircleFilled\" cx=\"67\" cy=\"78\" r=\"5\"/>\n</svg>";
    public static String s_vol  = "<svg id=\"volIcon\" viewBox=\"0 0 100 100\">\n<polygon class=\"iconPolyFilled\" points=\"75,20 75,80 25,50\"/>\n<rect class=\"iconRectFilled\" x=\"25\" y=\"40\" width=\"30\" height=\"20\"/>\n<circle class=\"iconCircleFilled\" cx=\"70\" cy=\"50\" r=\"10\"/>\n</svg>";
    public static String s_play = "<svg id=\"playPauseButton\" width=\"50\" height=\"50\" onclick=\"playPause()\" viewBox=\"20 20 70 60\">\n<polygon class=\"iconPolyFilled\" id=\"playButton\" points=\"33,25 33,75 80,50\"/>\n<rect class=\"iconRectFilled\" id=\"pauseButton1\" x=\"35\" y=\"25\" width=\"10\" height=\"50\"/>\n<rect class=\"iconRectFilled\" id=\"pauseButton2\" x=\"55\" y=\"25\" width=\"10\" height=\"50\"/>\n</svg>";
    
    public static String getLogo() {
        StringBuilder s_logo = new StringBuilder();
        s_logo.append("<svg onclick=\"window.location.assign('index.jsp')\" id=\"header_logo\" width=\"194\" height=\"60\" viewBox=\"0 0 300 100\">\\n<mask id=\"mask\" x=\"0\" y=\"0\" width=\"100\" height=\"100\">\\n<rect x=\"0\" y=\"0\" width=\"100\" height=\"100\" fill=\"#fff\"/>\\n<ellipse cx=\"2.5\"  cy=\"0\"   rx=\"30\" ry=\"51\" fill=\"#000\"/>\\n<ellipse cx=\"2.5\"  cy=\"100\" rx=\"30\" ry=\"51\" fill=\"#000\"/>\\n<ellipse cx=\"97.5\" cy=\"0\"   rx=\"70\" ry=\"51\" fill=\"#000\"/>\\n<ellipse cx=\"97.5\" cy=\"100\" rx=\"70\" ry=\"51\" fill=\"#000\"/>\\n</mask>\\n<rect class=\"iconRectFilled\" x=\"6\"   y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"12\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"18\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"24\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"30\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"36\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"42\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"48\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"54\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"60\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"66\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"72\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<rect class=\"iconRectFilled\" x=\"78\"  y=\"0\" width=\"3\" height=\"100\" mask=\"url(#mask)\"/>\\n<text class=\"iconText\" x=\"100\" y=\"68\" font-size=\"60\">sWave</text></svg>");
        return s_logo.toString();
    }
}
